### ISSUE TITLE
2.0 D3D Desktop Duplication unhandled exception

### ISSUE THREAD

**Issue by Drexen** [Toufool/AutoSplit#229]
Exception thrown when selecting D3D Desktop Duplication capture method:

Traceback (most recent call last):
  File "menu_bar.py", line 303, in <lambda>
  File "menu_bar.py", line 165, in __capture_method_changed
  File "capture_method\__init__.py", line 196, in change_capture_method
TypeError: DesktopDuplicationCaptureMethod.__init__() takes 1 positional argument but 2 were given

**Comment by Toufool** [comment]
This will be fixed in #228
