### ISSUE TITLE
crash when trying to open Video Capture

### ISSUE THREAD

**Issue by nictuku** [Toufool/AutoSplit#238]
**Describe the bug**

opening Video Capture Device, causes a crash every time.

**To Reproduce**

1. Go to File, Settings
2. Click on Video Capture Device
3. See error

**Expected behavior**
It should show my list of video capture devices. I use an Avermedia capture device.

**Screenshots and recordings**
![image](https://github.com/Toufool/AutoSplit/assets/202998/d58f1ee7-521f-46d1-9815-9845b2c1a937)

**Traceback or Crash Report**
If AutoSplit showed an exception traceback, please paste it here:

```
Traceback (most recent call last):

  File "menu_bar.py", line 307, in <lambda>

  File "menu_bar.py", line 165, in __capture_method_changed

  File "capture_method\__init__.py", line 196, in change_capture_method

  File "capture_method\VideoCaptureDeviceCaptureMethod.py", line 77, in __init__

  File "pygrabber\dshow_graph.py", line 371, in add_video_input_device

  File "pygrabber\dshow_graph.py", line 366, in __add_filter

  File "pygrabber\dshow_graph.py", line 299, in build_filter

  File "pygrabber\dshow_graph.py", line 288, in get_filter_by_index

ValueError: NULL COM pointer access

```

**Version (please complete the following information):**

- OS: Windows 10 Home 21H2 OS Build 19044.2965
- AutoSplit: 2.0.1

**AutoSplit Profile and Split Images**

I can't attach toml on github but here's it zipped [settings.zip](https://github.com/Toufool/AutoSplit/files/11525332/settings.zip)

**Additional context**

I have a webcam and the Avermedia video capture device connected. I also have an ndivida broadcaster software that creates additional virtual webcam..

**Comment by Avasam** [comment]
I've been able to replicate as well, since it suddenly started to happen, did you recently update to OBS 29.1.1 ? It broken the VirtualCam plugin and I think makes pygrabber crash when it tries to get the vcam's resolution.

**Comment by Avasam** [comment]
Update to OBS-VirtualCam to work with OBS 29.1: https://github.com/Avasam/obs-virtual-cam/releases/tag/3.1.0
