### ISSUE TITLE
Selecting "Video Capture Device" as Capture Method throws unhandled exception

### ISSUE THREAD

**Issue by BoredBanana** [Toufool/AutoSplit#252]
I am trying to select Video Capture Device as my capture method on a new install of version 2.2.0. As soon as the option is selected from the dropdown, I am presented with a popup with the below error. After dismissing the popup, the dropdown has Video Capture Device selected, but I cannot activate the second dropdown to choose my device. Selecting no other option produces this error.

```
Traceback (most recent call last):

  File "menu_bar.py", line 328, in <lambda>

  File "menu_bar.py", line 220, in __capture_method_changed

  File "capture_method\__init__.py", line 140, in change_capture_method

  File "capture_method\VideoCaptureDeviceCaptureMethod.py", line 93, in __init__

  File "pygrabber\dshow_graph.py", line 371, in add_video_input_device

  File "pygrabber\dshow_graph.py", line 366, in __add_filter

  File "pygrabber\dshow_graph.py", line 299, in build_filter

  File "pygrabber\dshow_graph.py", line 288, in get_filter_by_index

ValueError: NULL COM pointer access

```

![image](https://github.com/Toufool/AutoSplit/assets/47511880/05350745-6874-4719-b5de-84a4537c99ce)

- OS: Windows Version 10.0.19045 Build 19045
- AutoSplit: v2.2.0

[settings (as a text file).txt](https://github.com/Toufool/AutoSplit/files/12259638/settings.as.txt.file.txt)

**Comment by Avasam** [comment]
A fix will be included in the next release. You can try out and try the [latest dev builds](https://github.com/Toufool/AutoSplit/actions/workflows/lint-and-build.yml?query=event%3Apush+is%3Asuccess)
