### ISSUE TITLE
Incorrect Mapping of Screen Space on Multi-monitor Setups

### ISSUE THREAD

**Issue by Phobic-HR** [Toufool/AutoSplit#258]
**Description:**
Select Region and Select Window do not map to the correct screen space when used on some multi-monitor setups. This typically happens with larger monitors and when the largest monitor isn't in the top left.

**Reproduce Steps:**
-Open Window's Settings app and go to System
-Under Display arrange the windows so that the coordinate 0,0 would not be within the bounds of any window (see below)
-Start Autosplit and select any of the three screen capture methods
-Use the Select Region tool to select an area of any monitor

**Expected behaviour:**
The screen space selected matches the screen space displaced and compared against.

**Screenshots:**

![Screenshot of monitor arrangement.](https://github.com/Toufool/AutoSplit/assets/121365740/ed351f37-ef43-4181-b5a1-4acc2617b9be)

**Work Around:**
Move the largest monitor to the top and left in Settings app>System>Display.

**Extra Info:**
OS: Windows 10.0.19045
AutoSplit: v2.2.0

**Comment by Avasam** [comment]
Curious, I myself use multi-monitor setups (and a *very* unusual one that) and implemented the support when I started maintaining this project. We get the coords from Window's virtual desktop, hopefully this isn't a weird Windows edge-case. I'll try to replicate if I can.

**Comment by Tyrn18** [comment]
I tried going down the versions and this problem does not occur in version 1.5.1, anything above that produces the problem.

**Comment by jwwun** [comment]
I had two, no, three problems on 2.20, the region not capturing, the window not capturing anything but file explorer and the application itself, and probably this problem since I have a TV-sized second monitor 💢 . 
```
Traceback (most recent call last):

  File "AutoSplit.py", line 169, in <lambda>

  File "region_selection.py", line 116, in select_region

  File "capture_method\CaptureMethodBase.py", line 25, in reinitialize

  File "capture_method\WindowsGraphicsCaptureMethod.py", line 51, in __init__

OSError: [WinError -2147024809] The parameter is incorrect
```


I downgraded to AutoSplit_1.5.1 and it worked, somehow.

**Comment by Avasam** [comment]
I don't have a solution yet. But I have replicated on my Windows 11 laptop. So I can start investigating.
